### PR TITLE
add kind v1.26 support

### PR DESCRIPTION
**Pull request by dprotaso**

### CODE REVIEW

**Comment by dprotaso** [comment]
I fixed the `eventing` version that was installed to be `v1.8.x` - prior it was installing v1.7.x

**Review by cpanato — CHANGES_REQUESTED** [review]
we still need to have the 1.23 around

**Comment by vaikas** [comment]
Maybe just not test the knative spin up for the 1.23 step, but still test the kind setup?

**Comment by dprotaso** [comment]
done

**Review by vaikas — APPROVED** [review]
Awesomesauce, thanks!

**Review by cpanato — APPROVED** [review]
thanks

**Pull request merged**
