### PR TITLE
fix: Bump our min K8s version to v1.26 add k8s 1.28

### PR DESCRIPTION
**Pull request by MeenuyD**
Spin up the Kubernetes version to 1.28.
#318

### CODE REVIEW

**Comment by dprotaso** [comment]
@MeenuyD you'll have to gitsign your commits -

See: https://github.com/sigstore/gitsign

**Comment by dprotaso** [comment]
Looks like we can close this PR - since https://github.com/chainguard-dev/actions/pull/321 merged

**Comment by ReToCode** [comment]
Ah, sorry about that @MeenuyD. Haven't seen your PR.

**Comment by MeenuyD** [comment]
It's okay but I am waiting for the merge to see another pr get merged

**Comment by ReToCode** [comment]
I did the same PR in https://github.com/chainguard-dev/actions/pull/321 which is merged. So you should be able to continue your PR.

**Comment by k4leung4** [comment]
closing as obsolete due to https://github.com/chainguard-dev/actions/pull/321

**Pull request closed without merging**
