### PR TITLE
Fix docker inspect for latest runner images

### PR DESCRIPTION
**Pull request by skonto**
- Fixes https://github.com/chainguard-dev/actions/issues/446

### CODE REVIEW

**Comment by skonto** [comment]
Interesting this does not work on the actuall runner image due to jq version:

```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.IPAM.Config.[].Subnet | select(. | test("^[0-9]+\\."))      
```
I will update.

**Comment by skonto** [comment]
We might want to simplify using `grep -P` if we assume that this will not run with Kind on Mac.

**Review by mattmoor — APPROVED** [review]

**Comment by mattmoor** [comment]
thanks @skonto !

**Pull request merged**
